# Site
repository: jeevitha-force/resume
favicon: images/favicon.ico

# Personal info
name: Jeevitha
title: Sr. Salesforce Lightning Developer
email: jeevitha.force@gmail.com
website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: jekyll
github_username:  jeevitha-force
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: jeevitha-force
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jeevitha and I'm a Senior Salesforce Lightning Developer. A Polyglot Software Engineer with a penchant for Salesforce. I love coding and love to experiment with new technologies. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Salesforce</mark>, <mark>Mulesoft</mark>, <mark>Java</mark> and, <mark>JavaScript</mark> 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Salesforce and software engineering some of my other interests and hobbies are:
   - Yoga
   - Crafting
   - Movies

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: true
